### PR TITLE
refactor: nix flake for development

### PR DESCRIPTION
**Pull request by abaez**
The current nix set up was set up to use both nixos installation and
nix flake. 

However, it was set up in a way that is isolated from the
active usage and build of bonfire. The following patch changes quite a
bit the original nix flake. The purpose is to use the same tooling as that of
the current setup for bonfire with `just`. In doing so, focusing more on 
development environment for working with bonfire

The new set up takes the procedure of using `just setup` target with 
`WITH_DOCKER=no` to imitate a similar local setup. 

Note: while the nix flake does have sections to create nix packages and 
even container images to build for bonfire, it is not goal of the current PR
to make those sections to work.  

Ref: #405

### CODE REVIEW

**Comment by abaez** [comment]
@mayel I gone ahead and pushed up what I have for the nix set up. With this, you should be unblocked with using gitpod. As the development environment will be usable through nix as set with `WITH_DOCKER=no`. Updated the docs too for HACKING.md to reference the changes. I didn't update the deploy docs as this isn't yet ready for it. 

I wanted to touch deploy after this PR and fixing the draft issue on #403.

**Comment by mayel** [comment]
Awesome thanks @abaez ! Having a quick look but will only be able to give it a spin later on.

**Comment by mayel** [comment]
This is how far I've been able to get, maybe you can help me debug?

```
Code/Bonfire/bonfire-app > direnv allow

Code/Bonfire/bonfire-app > just nix-db-init
nix-db: line 1: PGDATA: unbound variable
error: Recipe `nix-db` failed on line 564 with exit code 127
```

**Comment by abaez** [comment]
@mayel good catch. The target can run after the `config/${mix_env}/{public,secret}.env` copied and modified files. It's required before that target is run.

I'll update the docs to place in the bottom of the after the rest is done.

**Comment by abaez** [comment]
@mayel going about the error message a bit more and looking at what's written  on the nix file, it seems direnv didn't set your environment variables correctly. Did you have a really long wait while direnv was running the nix packages downloads? It should take a while the first time. If you cancel, you may not get any variables populated. Do validate by running `echo $PGDATA`. If the variable is empty, then you haven't let direnv to complete its run. Open another shell and CD into the directory. Don't cancel download or try to stop direnv until the full setup is complete and you have a shell prompt ready. Try again with the echo for the variable.

**Comment by mayel** [comment]
yeah direnv didn't do anything, there was no wait, and `echo $PGDATA` is empty

**Comment by abaez** [comment]
@mayel also thought of that it's possible an old version is being used of direnv? I just recorded the following shell recording to help out https://asciinema.org/a/uq2JoAz4wlehiAurwYQcj650h

**Pull request merged**
