### PR TITLE
add nix dev instructions

### PR DESCRIPTION
**Pull request by happysalada**
This is a simple PR to add nix dev instructions.

There are still a couple of things that need to be considered.
- The assets folder does not have a package-lock.json. Do you want to commit it? Maybe you were thinking about changing package manager at some point? Or maybe you want people to be able to use different package managers?
- I'm not sure how messctl is supposed to be used, but nonetheless, it's available in the shell.
- the only environment variable I set is the MIX_ENV=dev. I'm not sure how to use the FORKS env var.

Let me know of course if you want to change anything.

### CODE REVIEW

**Comment by jjl** [comment]
Hello, thanks for the contribution.

I'm not a nix user but it looks fine at a scan.

Answers:
* There is a package-lock.json [in the assets directory](https://github.com/bonfire-networks/bonfire-app/blob/main/assets/package-lock.json)
* messctl is a little utility for programmatically updating the `.deps` files from which the final elixir dependencies list is compiled by the [mess](https://github.com/bonfire-networks/bonfire-app/blob/main/mess.exs) script. I believe the only use of it is [here](https://github.com/bonfire-networks/bonfire-app/blob/main/Makefile#L122) in the dep-* tasks which are used by some of the project developers and that the build does not rely on it.
* FORKS is used by the same developer tasks to determine where to find local forks of dependencies. You can set it to `./forks` but it's supposed to be guessed.

**Comment by happysalada** [comment]
Thanks for having a look!

My bad on the package-lock. I saw it was added to my gitfiles. It wasn't a new file, but a modified one.
Upon running the installation it modified the package-lock, I'm not sure why. I put a commit just to show the diff that it gave me. Maybe it's due to a different version of npm being used? Not sure.

Thanks for the explanation of the messctl tool and the FORK env var. I've pretty much added verbatim what you said in the README.

Let me know if anything.

**Comment by jjl** [comment]
i can't really speak for the frontend, don't really do much of it myself,  but it's probably just an oversight because things are changing a lot recently.

**Comment by happysalada** [comment]
Sure no problem. I committed it just in case it's interesting.
I'm available if you need anything changed.

**Comment by jjl** [comment]
i think the failure is unrelated to your changes so i've gone ahead and merged and asked someone to look at this test failure.

thanks!

**Comment by happysalada** [comment]
I checked it and it seemed unrelated yes.
Thanks a lot for the merge!

**Pull request merged**
