### PR TITLE
Fixes for bare metal documentation.

### PR DESCRIPTION
**Pull request by realkinetix**
- mention "just setup" step
- mention location of example nginx config
- mention adding in postgis extension manually
- mention possible issues with elixir 1.17 versions

### CODE REVIEW

**Comment by mayel** [comment]
Thanks ❤️

**Comment by lapineige** [comment]
Am I right to believe this applies to Yunohost installations ?
I will then update it (here https://github.com/YunoHost-Apps/bonfire_ynh/pull/5). Thanks !

**Comment by mayel** [comment]
@lapineige what part?

**Comment by lapineige** [comment]
All "manual install without docker" instructions I guess ?

**Pull request merged**
