### PR TITLE
Update test CI

### PR DESCRIPTION
**Pull request by fishinthecalculator**

### CODE REVIEW

**Comment by mayel** [comment]
Thanks for this, looks great! Only wondering about any pros/cons between manually installing docker vs using native container support like:
```
services:
      postgres:
        image: postgis/postgis:12-3.3-alpine

**Comment by fishinthecalculator** [comment]
> Thanks for this, looks great! Only wondering about any pros/cons between manually installing docker vs using native container support like:
> 
> ```
> services:
>       postgres:
>         image: postgis/postgis:12-3.3-alpine
> ```

I don't have a clear opinion on this topic. The rationale for having commands run from the `justfile` is that imho CI should run as close as possible to what we run in the CLI upon developing. This way as soon as the justfile is broken somehow CI also breaks and it also avoids duplicating implementation between the CI job and the development environment setup. If you have a different opinion I'd love to hear it!

**Comment by mayel** [comment]
@fishinthecalculator it may be relevant that `git-publish.sh` is used to push regular commits, not only when releasing a new version, so not sure if creating the tag there makes sense?

**Comment by fishinthecalculator** [comment]
@mayel thank you for the heads up, i had some rethinking about how to proceed. i'm starting to think that this MR should just be split between the test and the release part. I didn't remember about the `contrib-release` command you told me about until today and i wanted to start a discussion about how to stabilize the main branch

OT: is there some chat or some synchronous media where you hang out to talk about bonfire if I have some quick technical question? should I use https://campground.bonfire.cafe ?

**Comment by mayel** [comment]
sounds good! there's https://matrix.to/#/%23bonfire-tech%3Amatrix.org

**Comment by mayel** [comment]
Should we merge this one and then go from there?

**Comment by fishinthecalculator** [comment]
Yes I agree

**Pull request merged**
