### PR TITLE
remove bizarre executable perms on many files

### PR DESCRIPTION
**Pull request by peaceful-james**
Fixes https://github.com/bonfire-networks/bonfire-app/issues/927

### CODE REVIEW

**Comment by peaceful-james** [comment]
I just ran this script 

```
### Leaving these files as executable
# ./nix/shell.nix
# ./nix/module.nix
# ./nix/package.nix
# ./tool-versions-to-env.sh
# ./js-deps-get.sh
# ./git-publish.sh
# ./.git/hooks/pre-rebase.sample
# ./.git/hooks/pre-push.sample
# ./.git/hooks/fsmonitor-watchman.sample
# ./.git/hooks/prepare-commit-msg.sample
# ./.git/hooks/pre-applypatch.sample
# ./.git/hooks/pre-receive.sample
# ./.git/hooks/update.sample
# ./.git/hooks/pre-commit.sample
# ./.git/hooks/post-update.sample
# ./.git/hooks/push-to-checkout.sample
# ./.git/hooks/commit-msg.sample
# ./.git/hooks/applypatch-msg.sample
# ./.git/hooks/pre-merge-commit.sample
# ./flavours/reflow/config/deps.js.sh
# ./flavours/cooperation/config/deps.js.sh
# ./flavours/classic/config/deps.js.sh

echo "lets make the world a little safer"
chmod -x ./.github/ISSUE_TEMPLATE/other.md
chmod -x ./.github/ISSUE_TEMPLATE/bug_report.md
chmod -x ./.github/ISSUE_TEMPLATE/feature_request.md
chmod -x ./.github/workflows/release.yaml
chmod -x ./.tool-versions
chmod -x ./.gitignore
chmod -x ./README.md
chmod -x ./.erlang.cookie
chmod -x ./LICENSE
chmod -x ./.dockerignore
chmod -x ./test/test_helper.exs
chmod -x ./test/support/conn_case.ex
chmod -x ./test/support/channel_case.ex
chmod -x ./test/support/data_case.ex
chmod -x ./test/support/data_helpers.ex
chmod -x ./test/support/fake_helpers.ex
chmod -x ./.iex.exs
chmod -x ./mix.exs
chmod -x ./Dockerfile.dev
chmod -x ./docs/ARCHITECTURE.md
chmod -x ./docs/HACKING.md
chmod -x ./docs/index.html
chmod -x ./docs/MRF.md
chmod -x ./docs/GRAPHQL.md
chmod -x ./docker-compose.release.yml
chmod -x ./flavours/reflow/README.md
chmod -x ./flavours/reflow/repo/seeds/20210122131234_observe_classifications.exs
chmod -x ./flavours/reflow/repo/seeds.exs
chmod -x ./flavours/classic/README.md
chmod -x ./flavours/classic/repo/seeds.exs
chmod -x ./flavours/classic/DEPENDENCIES.md
chmod -x ./flavours/classic/config/bonfire_api_graphql.exs
chmod -x ./flavours/classic/config/templates/not_secret.env
chmod -x ./flavours/classic/config/templates/public.env
chmod -x ./flavours/classic/config/bonfire_common.exs
chmod -x ./flavours/classic/config/dev.exs
chmod -x ./flavours/classic/config/runtime.exs
chmod -x ./flavours/classic/config/bonfire_search.exs
chmod -x ./flavours/classic/config/activity_pub.exs
chmod -x ./flavours/classic/config/bonfire_federate_activitypub.exs
chmod -x ./flavours/classic/config/bonfire_quantify.exs
chmod -x ./flavours/classic/config/bonfire_ui.exs
chmod -x ./flavours/classic/config/bonfire_files.exs
chmod -x ./flavours/classic/config/deploy/Caddyfile2
chmod -x ./flavours/classic/config/prod.exs
chmod -x ./flavours/classic/config/bonfire_data.exs
chmod -x ./flavours/classic/config/bonfire_geolocate.exs
chmod -x ./flavours/classic/config/test.exs
chmod -x ./flavours/classic/config/config.exs
chmod -x ./flavours/classic/config/bonfire_mailer.exs
chmod -x ./flavours/classic/config/activity_pub_test.exs
chmod -x ./.sobelow/sobelow-vsn-check
chmod -x ./Dockerfile.release
chmod -x ./Makefile
chmod -x ./docker-compose.yml

```

**Comment by peaceful-james** [comment]
Should the `.nix` files be executable? @mayel

**Comment by peaceful-james** [comment]
ChatGPT says `.nix` files should not be executable.

```
chmod -x ./nix/shell.nix
chmod -x ./nix/module.nix
chmod -x ./nix/package.nix
```

**Comment by peaceful-james** [comment]
@mayel Point me at an issue, any issue. I need a north start before I go exploring deeper.

**Comment by mayel** [comment]
Thanls for taking a look :) It depends what part of the stack you'd prefer, so here are a few suggestions:
- GraphQL API with Absinthe: implementing for assocs that use Dataloader: https://github.com/bonfire-networks/bonfire-app/issues/915
- Backend (new extension/feature): basic spam detection (we have the MRF mechanisms for defining rules for incoming federation, but some extra protection as described would be useful also to deal with spammers/bots who may directly sign up to the instance and post from there).
- UI: I'd just pick a UI extension, run the tests and see if there's any you can figure out. We usually run them from within the main app, eg 
- `cd bonfire-app && mkdir extensions && cd extensions`
- `git clone https://github.com/bonfire-networks/bonfire_ui_reactions` 
- put `bonfire_ui_reactions = "extensions/bonfire_ui_reactions"` in `config/deps.path` to use the local dep
- `just test extensions/bonfire_ui_reactions/test` to run exunit

**Comment by peaceful-james** [comment]
I shall look at the graphql pagination issue.

**Pull request merged**
